# Configure regular ipcrawler options at the top of this file.

# nmap-append = '-T3'
# verbose = 1
# max-scans = 30

# Configure VHost discovery options
[vhost_discovery]
# Enable automatic VHost discovery via HTTP redirects
enabled = true

# Enable interactive prompts for /etc/hosts modification (set to false for non-interactive environments)
interactive_mode = true

# Automatically prompt to add discovered VHosts to /etc/hosts after scan
auto_add_hosts = true

# Request timeout for VHost discovery (seconds)
request_timeout = 10

# User agent for VHost discovery requests
user_agent = "ipcrawler-vhost-hunter/1.0"

# Backup /etc/hosts before making changes
backup_hosts_file = true

# Configure global options here.
# [global]
# username-wordlist = '/usr/share/seclists/Usernames/cirt-default-usernames.txt'

# Configure plugin options here.
# [dirbuster]
# threads = 50
# wordlist = [
# 	'/usr/share/seclists/Discovery/Web-Content/common.txt',
# 	'/usr/share/seclists/Discovery/Web-Content/big.txt',
# 	'/usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt'
# ]
